<a href="https://colab.research.google.com/github/Bala07-0ss/INTERNSHIP/blob/main/dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/Testing.csv")

In [4]:
df

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypertension
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Migraine
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cervical spondylosis
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Paralysis (brain hemorrhage)
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jaundice
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
16,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chicken pox
17,0,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Dengue
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Typhoid
19,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,hepatitis A
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis B
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis C
22,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis D
23,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis E
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Alcoholic hepatitis
25,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tuberculosis
26,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Common Cold
27,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Dimorphic hemmorhoids(piles)
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heart attack
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Varicose veins
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
40,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
41,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,Fungal infection

In [7]:
df.head(10)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma

In [8]:
df.tail(10)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
40,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
41,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,Fungal infection

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 43.8+ KB

In [10]:
df.shape

(42, 133)

In [11]:
df.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,...,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000
mean,0.166667,0.190476,0.023810,0.047619,0.023810,0.166667,0.142857,0.047619,0.047619,0.023810,...,0.023810,0.023810,0.023810,0.047619,0.023810,0.023810,0.023810,0.023810,0.047619,0.023810
std,0.377195,0.397437,0.154303,0.215540,0.154303,0.377195,0.354169,0.215540,0.215540,0.154303,...,0.154303,0.154303,0.154303,0.215540,0.154303,0.154303,0.154303,0.154303,0.215540,0.154303
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
df.isnull()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
df.fillna

<bound method NDFrame.fillna of     itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0         1          1                     1                    0          0
1         0          0                     0                    1          1
2         0          0                     0                    0          0
3         1          0                     0                    0          0
4         1          1                     0                    0          0
5         0          0                     0                    0          0
6         0          0                     0                    0          0
7         0          0                     0                    0          0
8         0          0                     0                    0          0
9         0          0                     0                    0          0
10        0          0                     0                    0          0
11        0          0                     0                    0          0
12        0          0                     0                    0          0
13        0          0                     0                    0          0
14        1          0                     0                    0          0
15        0          0                     0                    0          0
16        1          1                     0                    0          0
17        0          1                     0                    0          0
18        0          0                     0                    0          0
19        0          0                     0                    0          0
20        1          0                     0                    0          0
21        0          0                     0                    0          0
22        0          0                     0                    0          0
23        0          0                     0                    0          0
24        0          0                     0                    0          0
25        0          0                     0                    0          0
26        0          0                     0                    1          0
27        0          0                     0                    0          0
28        0          0                     0                    0          0
29        0          0                     0                    0          0
30        0          0                     0                    0          0
31        0          0                     0                    0          0
32        0          0                     0                    0          0
33        0          0                     0                    0          0
34        0          0                     0                    0          0
35        0          0                     0                    0          0
36        0          0                     0                    0          0
37        0          1                     0                    0          0
38        0          0                     0                    0          0
39        0          1                     0                    0          0
40        0          1                     0                    0          0
41        1          1                     0                    0          0

    chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0        0           0             0        0                 0  ...
1        1           0             0        0                 0  ...
2        0           0             1        1                 1  ...
3        0           0             0        0                 0  ...
4        0           0             1        0                 0  ...
5        0           0             0        0                 0  ...
6        0           0             0        0                 0  ...
7        0           0             0        0                 0  ...
8        0           0             0        0                 0  ...
9        0           0             0        0                 0  ...
10       0           0             0        0                 0  ...
11       0           0             0        1                 0  ...
12       0           0             0        0                 0  ...
13       0           0             0        0                 0  ...
14       0           0             0        0                 0  ...
15       1           0             0        0                 0  ...
16       0           0             0        0                 0  ...
17       1           1             0        0                 0  ...
18       1           0             0        0                 0  ...
19       0           1             0        0                 0  ...
20       0           0             0        0                 0  ...
21       0           0             0        0                 0  ...
22       0           1             0        0                 0  ...
23       0           1             0        0                 0  ...
24       0           0             0        0                 0  ...
25       1           0             0        0                 0  ...
26       1           0             0        0                 0  ...
27       1           0             0        0                 0  ...
28       0           0             0        0                 0  ...
29       0           0             0        0                 0  ...
30       0           0             0        0                 0  ...
31       0           0             0        0                 0  ...
32       0           0             0        0                 0  ...
33       0           0             0        0                 0  ...
34       0           1             0        0                 0  ...
35       0           0             0        0                 0  ...
36       0           0             0        0                 0  ...
37       0           0             0        0                 0  ...
38       0           0             0        0                 0  ...
39       0           1             0        0                 0  ...
40       0           0             0        0                 0  ...
41       0           0             0        0                 0  ...

    blackheads  scurring  skin_peeling  silver_like_dusting  \
0            0         0             0                    0
1            0         0             0                    0
2            0         0             0                    0
3            0         0             0                    0
4            0         0             0                    0
5            0         0             0                    0
6            0         0             0                    0
7            0         0             0                    0
8            0         0             0                    0
9            0         0             0                    0
10           0         0             0                    0
11           0         0             0                    0
12           0         0             0                    0
13           0         0             0                    0
14           0         0             0                    0
15           0         0             0                    0
16           0         0             0                    0
17           0         0             0                    0
18           0         0             0                    0
19           0         0             0                    0
20           0         0             0                    0
21           0         0             0                    0
22           0         0             0                    0
23           0         0             0                    0
24           0         0             0                    0
25           0         0             0                    0
26           0         0             0                    0
27           0         0             0                    0
28           0         0             0                    0
29           0         0             0                    0
30           0         0             0                    0
31           0         0             0                    0
32           0         0             0                    0
33           0         0             0                    0
34           0         0             0                    0
35           0         0             0                    0
36           0         0             0                    0
37           1         1             0                    0
38           0         0             0                    0
39           0         0             1                    1
40           0         0             0                    0
41           0         0             1                    0

    small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                      0                   0        0                     0
1                      0                   0        0                     0
2                      0                   0        0                     0
3                      0                   0        0                     0
4                      0                   0        0                     0
5                      0                   0        0                     0
6                      0                   0        0                     0
7                      0                   0        0                     0
8                      0                   0        0                     0
9                      0                   0        0                     0
10                     0                   0        0                     0
11                     0                   0        0                     0
12                     0                   0        0                     0
13                     0                   0        0                     0
14                     0                   0        0                     0
15                     0                   0        0                     0
16                     0                   0        0                     0
17                     0                   0        0                     0
18                     0                   0        0                     0
19                     0                   0        0                     0
20                     0                   0        0                     0
21                     0                   0        0                     0
22                     0                   0        0                     0
23                     0                   0        0                     0
24                     0                   0        0                     0
25                     0                   0        0                     0
26                     0                   0        0                     0
27                     0                   0        0                     0
28                     0                   0        0                     0
29                     0                   0        0                     0
30                     0                   0        0                     0
31                     0                   0        0                     0
32                     0                   0        0                     0
33                     0                   0        0                     0
34                     0                   0        0                     0
35                     0                   0        0                     0
36                     0                   0        0                     0
37                     0                   0        0                     0
38                     0                   0        0                     0
39                     1                   1        0                     0
40                     0                   0        1                     1
41                     0                   0        0                     1

    yellow_crust_ooze                                prognosis
0                   0                         Fungal infection
1                   0                                  Allergy
2                   0                                     GERD
3                   0                      Chronic cholestasis
4                   0                            Drug Reaction
5                   0                      Peptic ulcer diseae
6                   0                                     AIDS
7                   0                                Diabetes
8                   0                          Gastroenteritis
9                   0                         Bronchial Asthma
10                  0                            Hypertension
11                  0                                 Migraine
12                  0                     Cervical spondylosis
13                  0             Paralysis (brain hemorrhage)
14                  0                                 Jaundice
15                  0                                  Malaria
16                  0                              Chicken pox
17                  0                                   Dengue
18                  0                                  Typhoid
19                  0                              hepatitis A
20                  0                              Hepatitis B
21                  0                              Hepatitis C
22                  0                              Hepatitis D
23                  0                              Hepatitis E
24                  0                      Alcoholic hepatitis
25                  0                             Tuberculosis
26                  0                              Common Cold
27                  0                                Pneumonia
28                  0             Dimorphic hemmorhoids(piles)
29                  0                             Heart attack
30                  0                           Varicose veins
31                  0                           Hypothyroidism
32                  0                          Hyperthyroidism
33                  0                             Hypoglycemia
34                  0                          Osteoarthristis
35                  0                                Arthritis
36                  0  (vertigo) Paroymsal  Positional Vertigo
37                  0                                     Acne
38                  0                  Urinary tract infection
39                  0                                Psoriasis
40                  1                                 Impetigo
41                  0                         Fungal infection

[42 rows x 133 columns]>

In [16]:
df.dropna

<bound method DataFrame.dropna of     itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0         1          1                     1                    0          0
1         0          0                     0                    1          1
2         0          0                     0                    0          0
3         1          0                     0                    0          0
4         1          1                     0                    0          0
5         0          0                     0                    0          0
6         0          0                     0                    0          0
7         0          0                     0                    0          0
8         0          0                     0                    0          0
9         0          0                     0                    0          0
10        0          0                     0                    0          0
11        0          0                     0                    0          0
12        0          0                     0                    0          0
13        0          0                     0                    0          0
14        1          0                     0                    0          0
15        0          0                     0                    0          0
16        1          1                     0                    0          0
17        0          1                     0                    0          0
18        0          0                     0                    0          0
19        0          0                     0                    0          0
20        1          0                     0                    0          0
21        0          0                     0                    0          0
22        0          0                     0                    0          0
23        0          0                     0                    0          0
24        0          0                     0                    0          0
25        0          0                     0                    0          0
26        0          0                     0                    1          0
27        0          0                     0                    0          0
28        0          0                     0                    0          0
29        0          0                     0                    0          0
30        0          0                     0                    0          0
31        0          0                     0                    0          0
32        0          0                     0                    0          0
33        0          0                     0                    0          0
34        0          0                     0                    0          0
35        0          0                     0                    0          0
36        0          0                     0                    0          0
37        0          1                     0                    0          0
38        0          0                     0                    0          0
39        0          1                     0                    0          0
40        0          1                     0                    0          0
41        1          1                     0                    0          0

    chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0        0           0             0        0                 0  ...
1        1           0             0        0                 0  ...
2        0           0             1        1                 1  ...
3        0           0             0        0                 0  ...
4        0           0             1        0                 0  ...
5        0           0             0        0                 0  ...
6        0           0             0        0                 0  ...
7        0           0             0        0                 0  ...
8        0           0             0        0                 0  ...
9        0           0             0        0                 0  ...
10       0           0             0        0                 0  ...
11       0           0             0        1                 0  ...
12       0           0             0        0                 0  ...
13       0           0             0        0                 0  ...
14       0           0             0        0                 0  ...
15       1           0             0        0                 0  ...
16       0           0             0        0                 0  ...
17       1           1             0        0                 0  ...
18       1           0             0        0                 0  ...
19       0           1             0        0                 0  ...
20       0           0             0        0                 0  ...
21       0           0             0        0                 0  ...
22       0           1             0        0                 0  ...
23       0           1             0        0                 0  ...
24       0           0             0        0                 0  ...
25       1           0             0        0                 0  ...
26       1           0             0        0                 0  ...
27       1           0             0        0                 0  ...
28       0           0             0        0                 0  ...
29       0           0             0        0                 0  ...
30       0           0             0        0                 0  ...
31       0           0             0        0                 0  ...
32       0           0             0        0                 0  ...
33       0           0             0        0                 0  ...
34       0           1             0        0                 0  ...
35       0           0             0        0                 0  ...
36       0           0             0        0                 0  ...
37       0           0             0        0                 0  ...
38       0           0             0        0                 0  ...
39       0           1             0        0                 0  ...
40       0           0             0        0                 0  ...
41       0           0             0        0                 0  ...

    blackheads  scurring  skin_peeling  silver_like_dusting  \
0            0         0             0                    0
1            0         0             0                    0
2            0         0             0                    0
3            0         0             0                    0
4            0         0             0                    0
5            0         0             0                    0
6            0         0             0                    0
7            0         0             0                    0
8            0         0             0                    0
9            0         0             0                    0
10           0         0             0                    0
11           0         0             0                    0
12           0         0             0                    0
13           0         0             0                    0
14           0         0             0                    0
15           0         0             0                    0
16           0         0             0                    0
17           0         0             0                    0
18           0         0             0                    0
19           0         0             0                    0
20           0         0             0                    0
21           0         0             0                    0
22           0         0             0                    0
23           0         0             0                    0
24           0         0             0                    0
25           0         0             0                    0
26           0         0             0                    0
27           0         0             0                    0
28           0         0             0                    0
29           0         0             0                    0
30           0         0             0                    0
31           0         0             0                    0
32           0         0             0                    0
33           0         0             0                    0
34           0         0             0                    0
35           0         0             0                    0
36           0         0             0                    0
37           1         1             0                    0
38           0         0             0                    0
39           0         0             1                    1
40           0         0             0                    0
41           0         0             1                    0

    small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                      0                   0        0                     0
1                      0                   0        0                     0
2                      0                   0        0                     0
3                      0                   0        0                     0
4                      0                   0        0                     0
5                      0                   0        0                     0
6                      0                   0        0                     0
7                      0                   0        0                     0
8                      0                   0        0                     0
9                      0                   0        0                     0
10                     0                   0        0                     0
11                     0                   0        0                     0
12                     0                   0        0                     0
13                     0                   0        0                     0
14                     0                   0        0                     0
15                     0                   0        0                     0
16                     0                   0        0                     0
17                     0                   0        0                     0
18                     0                   0        0                     0
19                     0                   0        0                     0
20                     0                   0        0                     0
21                     0                   0        0                     0
22                     0                   0        0                     0
23                     0                   0        0                     0
24                     0                   0        0                     0
25                     0                   0        0                     0
26                     0                   0        0                     0
27                     0                   0        0                     0
28                     0                   0        0                     0
29                     0                   0        0                     0
30                     0                   0        0                     0
31                     0                   0        0                     0
32                     0                   0        0                     0
33                     0                   0        0                     0
34                     0                   0        0                     0
35                     0                   0        0                     0
36                     0                   0        0                     0
37                     0                   0        0                     0
38                     0                   0        0                     0
39                     1                   1        0                     0
40                     0                   0        1                     1
41                     0                   0        0                     1

    yellow_crust_ooze                                prognosis
0                   0                         Fungal infection
1                   0                                  Allergy
2                   0                                     GERD
3                   0                      Chronic cholestasis
4                   0                            Drug Reaction
5                   0                      Peptic ulcer diseae
6                   0                                     AIDS
7                   0                                Diabetes
8                   0                          Gastroenteritis
9                   0                         Bronchial Asthma
10                  0                            Hypertension
11                  0                                 Migraine
12                  0                     Cervical spondylosis
13                  0             Paralysis (brain hemorrhage)
14                  0                                 Jaundice
15                  0                                  Malaria
16                  0                              Chicken pox
17                  0                                   Dengue
18                  0                                  Typhoid
19                  0                              hepatitis A
20                  0                              Hepatitis B
21                  0                              Hepatitis C
22                  0                              Hepatitis D
23                  0                              Hepatitis E
24                  0                      Alcoholic hepatitis
25                  0                             Tuberculosis
26                  0                              Common Cold
27                  0                                Pneumonia
28                  0             Dimorphic hemmorhoids(piles)
29                  0                             Heart attack
30                  0                           Varicose veins
31                  0                           Hypothyroidism
32                  0                          Hyperthyroidism
33                  0                             Hypoglycemia
34                  0                          Osteoarthristis
35                  0                                Arthritis
36                  0  (vertigo) Paroymsal  Positional Vertigo
37                  0                                     Acne
38                  0                  Urinary tract infection
39                  0                                Psoriasis
40                  1                                 Impetigo
41                  0                         Fungal infection

[42 rows x 133 columns]>

In [17]:
df.drop_duplicates()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypertension
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Migraine
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cervical spondylosis
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Paralysis (brain hemorrhage)
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jaundice
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
16,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chicken pox
17,0,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Dengue
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Typhoid
19,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,hepatitis A
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis B
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis C
22,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis D
23,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis E
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Alcoholic hepatitis
25,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tuberculosis
26,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Common Cold
27,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Dimorphic hemmorhoids(piles)
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heart attack
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Varicose veins
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
40,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
41,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,Fungal infection

In [23]:
df.replace(1,2)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,2,2,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,2,2,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,2,2,2,...,0,0,0,0,0,0,0,0,0,GERD
3,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,2,2,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypertension
11,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,Migraine
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cervical spondylosis
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Paralysis (brain hemorrhage)
14,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jaundice
15,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
16,2,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chicken pox
17,0,2,0,0,0,2,2,0,0,0,...,0,0,0,0,0,0,0,0,0,Dengue
18,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Typhoid
19,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,hepatitis A
20,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis B
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis C
22,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis D
23,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis E
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Alcoholic hepatitis
25,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tuberculosis
26,0,0,0,2,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Common Cold
27,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Dimorphic hemmorhoids(piles)
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heart attack
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Varicose veins
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,0,2,0,0,0,0,0,0,0,0,...,2,2,0,0,0,0,0,0,0,Acne
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,0,2,0,0,0,0,2,0,0,0,...,0,0,2,2,2,2,0,0,0,Psoriasis
40,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,Impetigo
41,2,2,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,2,0,Fungal infection

In [25]:
df.query("itching < 1")

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Peptic ulcer diseae
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,AIDS
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Gastroenteritis
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Bronchial Asthma
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypertension
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Migraine
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cervical spondylosis
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Paralysis (brain hemorrhage)
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
17,0,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Dengue
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Typhoid
19,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,hepatitis A
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis C
22,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis D
23,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis E
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Alcoholic hepatitis
25,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tuberculosis
26,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Common Cold
27,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Dimorphic hemmorhoids(piles)
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heart attack
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Varicose veins
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hyperthyroidism
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypoglycemia
34,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Osteoarthristis
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
37,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
39,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
40,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo